# Generated by Django 5.2.12 on 2026-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('specialty', models.CharField(max_length=120)),
                ('crm', models.CharField(max_length=20)),
            ],
        ),
    ]
